global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'windows'
    static_configs:
      - targets: ['localhost:9182']

  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['localhost:9835']

  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
